#!/usr/bin/env bash
set -euo pipefail

OUTPUT_FILE="${1:-.deploy/backend.env}"

mkdir -p "$(dirname "$OUTPUT_FILE")"
> "$OUTPUT_FILE"

write_kv() {
  local key="$1"
  local value="${2-}"
  value="${value//$'\r'/}"
  value="${value//$'\n'/\\n}"
  printf '%s=%s\n' "$key" "$value" >> "$OUTPUT_FILE"
}

write_kv NODE_ENV production

keys=(
  KB_API_HOST
  KB_API_PORT
  KB_TRUST_PROXY
  KB_BODY_LIMIT
  KB_PUBLIC_BASE_URL
  KB_ALLOWED_ORIGINS
  KB_ACCESS_TOKEN_TTL_SECONDS
  KB_REFRESH_TOKEN_TTL_SECONDS
  KB_DATABASE_URL
  KB_DATABASE_SSL_MODE
  KB_DATABASE_SSL_REJECT_UNAUTHORIZED
  SUPABASE_URL
  SUPABASE_SERVICE_ROLE_KEY
  KB_SUPABASE_STORAGE_BUCKET
  KB_SUPABASE_CACHE_CONTROL
  KB_ADMIN_EMAIL
  KB_ADMIN_PASSWORD
  KB_JWT_ACCESS_SECRET
  KB_JWT_REFRESH_SECRET
  KB_INTERNAL_SERVICE_TOKEN
  KB_CREDENTIALS_ENCRYPTION_KEY
  KB_GITHUB_APP_INSTALL_URL
  KB_GITHUB_APP_CLIENT_ID
  KB_GITHUB_APP_CLIENT_SECRET
  KB_GITHUB_APP_ID
  KB_GITHUB_APP_PRIVATE_KEY
  KB_GITHUB_APP_WEBHOOK_SECRET
  KB_GITHUB_APP_CALLBACK_PATH
  KB_WPP_WEBHOOK_API_KEY
  EVOLUTION_API_URL
  EVOLUTION_API_KEY
  EVOLUTION_INSTANCE_NAME
  EVOLUTION_API_PUBLIC_URL
  KB_TELEGRAM_BOT_TOKEN
  KB_TELEGRAM_WEBHOOK_TOKEN
  KB_TELEGRAM_CHAT_ID
  KB_REVIEW_AI_PROVIDER
  KB_REVIEW_AI_BASE_URL
  KB_REVIEW_AI_MODEL
  KB_REVIEW_AI_API_KEY
  KB_CONVERSATION_AI_PROVIDER
  KB_CONVERSATION_AI_BASE_URL
  KB_CONVERSATION_AI_MODEL
  KB_CONVERSATION_AI_API_KEY
)

for key in "${keys[@]}"; do
  write_kv "$key" "${!key:-}"
done

chmod 600 "$OUTPUT_FILE"
