#!/usr/bin/env bash
set -euo pipefail

OUTPUT_FILE="${1:-.deploy/backend.env}"

mkdir -p "$(dirname "$OUTPUT_FILE")"
> "$OUTPUT_FILE"

write_kv() {
  local key="$1"
  local value="${2-}"
  value="${value//$'\r'/}"
  value="${value//$'\n'/\\n}"
  # Use single quotes to prevent shell expansion of special chars like $
  printf '%s='"'"'%s'"'"'\n' "$key" "$value" >> "$OUTPUT_FILE"
}

write_kv NODE_ENV production

keys=(
  KB_API_HOST
  KB_API_PORT
  KB_TRUST_PROXY
  KB_BODY_LIMIT
  KB_PUBLIC_BASE_URL
  KB_API_PUBLIC_BASE_URL
  KB_ALLOWED_ORIGINS
  KB_ALLOWED_EXTENSION_IDS
  KB_ACCESS_TOKEN_TTL_SECONDS
  KB_REFRESH_TOKEN_TTL_SECONDS
  KB_DATABASE_URL
  KB_DATABASE_SSL_MODE
  KB_DATABASE_SSL_REJECT_UNAUTHORIZED
  SUPABASE_URL
  SUPABASE_SERVICE_ROLE_KEY
  KB_SUPABASE_STORAGE_BUCKET
  KB_SUPABASE_CACHE_CONTROL
  KB_ADMIN_EMAIL
  KB_ADMIN_PASSWORD
  KB_JWT_ACCESS_SECRET
  KB_JWT_REFRESH_SECRET
  KB_GOOGLE_OAUTH_CLIENT_ID
  KB_GOOGLE_OAUTH_CLIENT_SECRET
  KB_GOOGLE_OAUTH_REDIRECT_URI
  KB_INTERNAL_SERVICE_TOKEN
  KB_CREDENTIALS_ENCRYPTION_KEY
  KB_GITHUB_APP_INSTALL_URL
  KB_GITHUB_APP_CLIENT_ID
  KB_GITHUB_APP_CLIENT_SECRET
  KB_GITHUB_APP_ID
  KB_GITHUB_APP_PRIVATE_KEY
  KB_GITHUB_APP_WEBHOOK_SECRET
  KB_GITHUB_APP_CALLBACK_PATH
  KB_GITHUB_BACKFILL_LIMIT
  KB_WPP_WEBHOOK_API_KEY
  EVOLUTION_API_URL
  EVOLUTION_API_KEY
  EVOLUTION_INSTANCE_NAME
  EVOLUTION_API_PUBLIC_URL
  KB_TELEGRAM_BOT_TOKEN
  KB_TELEGRAM_WEBHOOK_TOKEN
  KB_TELEGRAM_CHAT_ID
  KB_REVIEW_AI_PROVIDER
  KB_REVIEW_AI_BASE_URL
  KB_REVIEW_AI_MODEL
  KB_REVIEW_AI_API_KEY
  KB_CONVERSATION_AI_PROVIDER
  KB_CONVERSATION_AI_BASE_URL
  KB_CONVERSATION_AI_MODEL
  KB_CONVERSATION_AI_API_KEY
  KB_PROJECT_BRIEF_AI_PROVIDER
  KB_PROJECT_BRIEF_AI_BASE_URL
  KB_PROJECT_BRIEF_AI_MODEL
  KB_PROJECT_BRIEF_AI_API_KEY
  KB_PR_CONTEXT_AI_PROVIDER
  KB_PR_CONTEXT_AI_BASE_URL
  KB_PR_CONTEXT_AI_MODEL
  KB_PR_CONTEXT_AI_API_KEY
  KB_EMBEDDING_AI_PROVIDER
  KB_EMBEDDING_AI_BASE_URL
  KB_EMBEDDING_AI_MODEL
  KB_EMBEDDING_AI_API_KEY
  KB_SEARCH_MIN_SIMILARITY
  KB_SEARCH_CANDIDATE_LIMIT_MULTIPLIER
  KB_SEARCH_HYBRID_VECTOR_WEIGHT
  KB_SEARCH_HYBRID_KEYWORD_WEIGHT
  KB_RAG_MIN_SIMILARITY
  KB_RAG_CANDIDATE_LIMIT
  KB_RAG_HYBRID_VECTOR_WEIGHT
  KB_RAG_HYBRID_KEYWORD_WEIGHT
  KB_RAG_TOP_CHUNKS_LIMIT
  KB_AUDIO_AI_PROVIDER
  KB_AUDIO_AI_BASE_URL
  KB_AUDIO_AI_MODEL
  KB_AUDIO_AI_API_KEY
  KB_RABBITMQ_URL
  KB_RABBITMQ_USER
  KB_RABBITMQ_PASSWORD
  KB_RABBITMQ_PORT
  KB_RABBITMQ_MANAGEMENT_PORT
  KB_DISABLE_EMBEDDING_WORKER
  KB_VAPID_PUBLIC_KEY
  KB_VAPID_PRIVATE_KEY
  ASAAS_ACCESS_TOKEN
  ASAAS_BASE_URL
  ASAAS_WEBHOOK_TOKEN
  ASAAS_CUSTOMER_NOTIFICATIONS_DISABLED
  STRIPE_SECRET_KEY
  STRIPE_PUBLISHABLE_KEY
  STRIPE_WEBHOOK_SECRET
  ONLY_STRIPE
  CHANGE_SUBSCRIPTION_WORKER_AUTORUN
  BILLING_WORKER_AUTORUN
  MAX_DAYS_PAST_DUE
  WEBHOOK_OUTBOX_RELAY_AUTORUN
  WEBHOOK_OUTBOX_RELAY_CRON
  WEBHOOK_OUTBOX_RELAY_TIMEZONE
  WEBHOOK_OUTBOX_RELAY_BATCH_SIZE
  WEBHOOK_OUTBOX_RELAY_MIN_AGE_SECONDS
  WEBHOOK_OUTBOX_RELAY_MAX_ATTEMPTS
  # Email provider configuration
  KB_EMAIL_PROVIDER
  KB_EMAIL_RESEND_API_KEY
  KB_EMAIL_FROM
  KB_EMAIL_SMTP_HOST
  KB_EMAIL_SMTP_PORT
  KB_EMAIL_SMTP_USER
  KB_EMAIL_SMTP_PASS
  KB_EMAIL_SMTP_SECURE
  KB_EMAIL_QUEUE_EXCHANGE
  KB_EMAIL_QUEUE_NAME
  KB_EMAIL_QUEUE_ROUTING_KEY
  KB_EMAIL_WORKER_AUTORUN
  DEV_EMAIL
  DEV_EMAIL_INTERCEPT
  # Test email authentication secret
  KB_TEST_EMAIL_AUTH_SECRET
  # Email branding
  APP_NAME
  APP_LOGO_URL
)

for key in "${keys[@]}"; do
  write_kv "$key" "${!key:-}"
done

chmod 600 "$OUTPUT_FILE"
