export const UI_MESSAGES = {
  // Success messages
  PROJECT_DELETED: 'Project deleted successfully.',
  PROJECT_CREATED: 'Project created successfully.',
  PROJECT_UPDATED: 'Project updated successfully.',
  FOLDER_DELETED: 'Folder deleted successfully.',
  FOLDER_CREATED: 'Folder created successfully.',
  FOLDER_UPDATED: 'Folder updated successfully.',
  NOTE_DELETED: 'Note deleted successfully.',
  NOTE_CREATED: 'Note created successfully.',
  NOTE_UPDATED: 'Note updated successfully.',
  NOTE_PINNED: 'Note pinned.',
  NOTE_UNPINNED: 'Note unpinned.',
  REPOSITORIES_SAVED: 'Repositories saved successfully.',
  WEBHOOK_CREATED: 'Webhook created.',
  WEBHOOK_UPDATED: 'Webhook updated.',
  WEBHOOK_DELETED: 'Webhook deleted.',
  WORKSPACE_CREATED: 'Workspace created successfully.',

  // Error messages
  COULD_NOT_DELETE_PROJECT: 'Could not delete the project.',
  COULD_NOT_DELETE_FOLDER: 'Could not delete the folder.',
  COULD_NOT_DELETE_NOTE: 'Could not delete the note.',
  COULD_NOT_LOAD_NOTE_FOR_EDITING: 'Could not load the note for editing.',
  COULD_NOT_UPDATE_NOTE_STATUS: 'Could not update the note status.',
  COULD_NOT_TOGGLE_PIN_STATUS: 'Could not toggle pin status.',
  COULD_NOT_SAVE_REPOSITORIES: 'Could not save the selected repositories.',
  COULD_NOT_AUTHENTICATE: 'Could not authenticate with these details.',
  COULD_NOT_CREATE_WORKSPACE: 'Could not create the workspace.',
  COULD_NOT_UPDATE_REMINDER_STATUS: 'Could not update the reminder status.',
  COULD_NOT_GENERATE_PROJECT_BRIEF: 'Could not generate the project brief.',
  COULD_NOT_LOAD_NOTES_FOR_SEARCH: 'Could not load notes for this search.',

  // Validation messages
  INBOX_CANNOT_BE_CHANGED: 'Inbox cannot be changed.',
  DELETE_OR_MOVE_PROJECT_NOTES: 'Delete or move the project notes before removing it.',

  // UI labels
  PROJECTS: 'Projects',
  ALL: 'All',
  OPEN: 'Open',
  QUICK_NOTE: 'Quick note',
  NEW_PROJECT: 'New project',
  NEW_NOTE: 'New note',
  NEW_FOLDER: 'New folder',
  FOLDERS: 'Folders',
  SELECT_PROJECT: 'Select project',
  FILTER_BY_STATUS: 'Filter by status',
  FILTER_BY_CATEGORY: 'Filter by category',
  SEARCH_RESULTS: 'Search Results',
  SEARCH_NOTES_IN_PROJECT: 'Search notes in project',
  SEARCH_IN: 'Search in',
  SEARCH_ACROSS_ALL_PROJECTS: 'Search across all projects',
  NOTES_FROM_ALL_PROJECTS: 'Notes from all projects',
  ALL_PROJECT_NOTES: 'All project notes',
  AND_DESCENDANT_FOLDERS: 'and descendant folders',
  NO_NOTES_FOUND_FOR_SEARCH: 'No notes found for this search.',
  NO_TIMELINE_ITEMS_FOR_CATEGORY: 'No timeline items for this category.',
  TOTAL: 'total',
  CANCEL: 'Cancel',
  CONFIRM_DELETION: 'Confirm deletion',
  DELETE_PROJECT: 'Delete project',
  DELETE_FOLDER: 'Delete folder',
  DELETE_NOTE: 'Delete note',
  RESOLVE_ALL: 'Resolve all',
  ARCHIVE_ALL: 'Archive all',
  RESOLVE_ALL_ITEMS: 'Resolve all items',
  ARCHIVE_ALL_ITEMS: 'Archive all items',
  EDIT: 'Edit',
  PIN: 'Pin',
  UNPIN: 'Unpin',
  PINNED: 'Pinned',
  PINNED_NOTE: 'Pinned Note',
} as const;

export type UIMessageKey = keyof typeof UI_MESSAGES;
