import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as vscode from 'vscode';

import { logInfo, toMessage } from '../../error-reporter';
import { watchFile } from '../../utils/watcher';

const KOTE_CONFIG_DIR = path.join(os.homedir(), '.config', 'kote');
const KOTE_HOOKS_DIR = path.join(KOTE_CONFIG_DIR, 'hooks');
const SESSION_START_SCRIPT = path.join(KOTE_HOOKS_DIR, 'session-start.js');
const ACTIVE_SESSION_START_PATH = path.join(KOTE_CONFIG_DIR, 'active-session-start.json');

export type ActiveSessionStartInfo = {
  targetProvider: string;
  timestamp: number;
  cwd?: string;
};

function createRunnerScript(): void {
  try {
    if (!fs.existsSync(KOTE_HOOKS_DIR)) {
      fs.mkdirSync(KOTE_HOOKS_DIR, { recursive: true });
    }

    const scriptContent = `#!/usr/bin/env node
/**
 * Kote Session Start Hook Bridge
 * Auto-generated by Kote VS Code extension.
 */
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import https from 'node:https';
import http from 'node:http';

const CONFIG_PATH = path.join(os.homedir(), '.config', 'kb', 'config.json');
const LAST_HANDOFF_PATH = path.join(os.homedir(), '.config', 'kote', 'last-handoff.md');
const ACTIVE_START_PATH = path.join(os.homedir(), '.config', 'kote', 'active-session-start.json');

function readConfig() {
  try {
    if (fs.existsSync(CONFIG_PATH)) {
      return JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
    }
  } catch {}
  return null;
}

function notifySessionStart(provider) {
  try {
    const data = JSON.stringify({
      targetProvider: provider,
      timestamp: Date.now(),
      cwd: process.cwd(),
    });
    fs.writeFileSync(ACTIVE_START_PATH, data, 'utf8');
  } catch {}
}

async function fetchHandoff(provider) {
  const config = readConfig();
  if (!config || (!config.cookies?.kb_access_token && !config.cookies?.kb_refresh_token)) {
    return null;
  }

  const apiBase = (config.apiUrl || 'https://knowledgebase.sbs/kote/api').replace(/\\/$/, '');
  const cleanBase = apiBase.endsWith('/api') ? apiBase : \`\${apiBase}/api\`;
  const url = new URL(\`\${cleanBase}/notes/session-handoff\`);

  const cookies = [];
  if (config.cookies?.kb_access_token) cookies.push(\`kb_access_token=\${config.cookies.kb_access_token}\`);
  if (config.cookies?.kb_refresh_token) cookies.push(\`kb_refresh_token=\${config.cookies.kb_refresh_token}\`);

  const postData = JSON.stringify({
    provider,
    autoDetectPrevious: true,
    workspaceSlug: config.workspaceSlug || 'default',
  });

  return new Promise((resolve) => {
    const isHttps = url.protocol === 'https:';
    const req = (isHttps ? https : http).request(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Cookie': cookies.join('; '),
        'Content-Length': Buffer.byteLength(postData),
      },
      timeout: 4000,
    }, (res) => {
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        try {
          const parsed = JSON.parse(data);
          if (parsed && parsed.handoffMarkdown) {
            resolve(parsed);
            return;
          }
        } catch {}
        resolve(null);
      });
    });

    req.on('error', () => resolve(null));
    req.on('timeout', () => { req.destroy(); resolve(null); });
    req.write(postData);
    req.end();
  });
}

async function main() {
  const provider = process.env.AGENT_HARNESS || 'unknown';
  notifySessionStart(provider);

  try {
    const handoff = await fetchHandoff(provider);
    if (handoff && handoff.handoffMarkdown) {
      const sourceProvider = handoff.sourceProvider || 'Previous Agent';
      fs.writeFileSync(LAST_HANDOFF_PATH, handoff.handoffMarkdown, 'utf8');

      process.stdout.write(\`\\n[Kote] Session handoff loaded from \${sourceProvider}\\n\`);
      process.stdout.write(handoff.handoffMarkdown + '\\n');
    }
  } catch {}
}

void main();
`;

    fs.writeFileSync(SESSION_START_SCRIPT, scriptContent, { mode: 0o755 });
  } catch (err) {
    logInfo('Hooks', `Failed to write session-start script: ${toMessage(err)}`);
  }
}

function registerClaudeCodeHook(): boolean {
  try {
    const claudeDir = path.join(os.homedir(), '.claude');
    if (!fs.existsSync(claudeDir)) return false;

    const settingsPath = path.join(claudeDir, 'settings.json');
    let settings: Record<string, any> = {};
    if (fs.existsSync(settingsPath)) {
      try {
        settings = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
      } catch {}
    }

    if (!settings.hooks) settings.hooks = {};
    const command = `node "${SESSION_START_SCRIPT}"`;
    if (settings.hooks.session_start !== command) {
      settings.hooks.session_start = command;
      fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2), 'utf8');
      return true;
    }
  } catch (err) {
    logInfo('Hooks', `Failed to register Claude Code hook: ${toMessage(err)}`);
  }
  return false;
}

function registerAntigravityHook(): boolean {
  try {
    const agDir = path.join(os.homedir(), '.gemini', 'antigravity-cli');
    if (!fs.existsSync(agDir)) return false;

    const hooksDir = path.join(agDir, 'hooks');
    if (!fs.existsSync(hooksDir)) {
      fs.mkdirSync(hooksDir, { recursive: true });
    }

    const hookTarget = path.join(hooksDir, 'session-start.js');
    if (!fs.existsSync(hookTarget)) {
      fs.copyFileSync(SESSION_START_SCRIPT, hookTarget);
      return true;
    }
  } catch (err) {
    logInfo('Hooks', `Failed to register Antigravity hook: ${toMessage(err)}`);
  }
  return false;
}

function registerOpenCodeHook(): boolean {
  try {
    const opencodeDir = path.join(os.homedir(), '.config', 'opencode');
    if (!fs.existsSync(opencodeDir)) return false;

    const pluginsDir = path.join(opencodeDir, 'plugins');
    if (!fs.existsSync(pluginsDir)) {
      fs.mkdirSync(pluginsDir, { recursive: true });
    }

    const pluginTarget = path.join(pluginsDir, 'kote-session-handoff.js');
    if (!fs.existsSync(pluginTarget)) {
      fs.copyFileSync(SESSION_START_SCRIPT, pluginTarget);
      return true;
    }
  } catch (err) {
    logInfo('Hooks', `Failed to register OpenCode hook: ${toMessage(err)}`);
  }
  return false;
}

export async function autoRegisterHarnessHooks(): Promise<{ registered: string[] }> {
  createRunnerScript();

  const registered: string[] = [];
  if (registerClaudeCodeHook()) registered.push('claude-code');
  if (registerAntigravityHook()) registered.push('antigravity');
  if (registerOpenCodeHook()) registered.push('opencode');

  if (registered.length > 0) {
    logInfo('Hooks', `Auto-registered SessionStart hooks for: ${registered.join(', ')}`);
  }

  return { registered };
}

export function watchActiveSessionStarts(
  callback: (info: ActiveSessionStartInfo) => void
): vscode.Disposable {
  try {
    if (!fs.existsSync(KOTE_CONFIG_DIR)) {
      fs.mkdirSync(KOTE_CONFIG_DIR, { recursive: true });
    }
    if (!fs.existsSync(ACTIVE_SESSION_START_PATH)) {
      fs.writeFileSync(ACTIVE_SESSION_START_PATH, '{}', 'utf8');
    }
  } catch {}

  let debounceTimer: NodeJS.Timeout | undefined;

  return watchFile(ACTIVE_SESSION_START_PATH, () => {
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      try {
        if (!fs.existsSync(ACTIVE_SESSION_START_PATH)) return;
        const raw = fs.readFileSync(ACTIVE_SESSION_START_PATH, 'utf8');
        const info = JSON.parse(raw) as ActiveSessionStartInfo;
        if (info && info.targetProvider && info.timestamp) {
          callback(info);
        }
      } catch {}
    }, 100);
  });
}
